# Linter Options
options:
  # Set the formatter to 'html'
  formatter: html
# File Options
files:
  include: '**/*.s+(a|c)ss'
  ignore:
    - '**/vendor/**/*.s+(a|c)ss'
# Rule Configuration
rules:
  leading-zero:
    include: true
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  mixins-before-declarations:
    - 0

  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 2
  no-css-comments: 0
  class-name-format: 0
  hex-notation:
    - 2
    -
      style: uppercase
  indentation:
    - 2
    -
      size: 2
  property-sort-order:
    - 1
    -
      order:
        - 'position'
        - 'top'
        - 'right'
        - 'bottom'
        - 'left'
        - 'z-index'
        - 'display'
        - 'flex'
        - 'flex-basis'
        - 'flex-direction'
        - 'flex-flow'
        - 'flex-grow'
        - 'flex-shrink'
        - 'flex-wrap'
        - 'align-content'
        - 'align-items'
        - 'align-self'
        - 'justify-content'
        - 'width'
        - 'height'
        - 'max-width'
        - 'max-height'
        - 'min-width'
        - 'min-height'
        - 'padding'
        - 'padding-top'
        - 'padding-right'
        - 'padding-bottom'
        - 'padding-left'
        - 'margin'
        - 'margin-top'
        - 'margin-right'
        - 'margin-bottom'
        - 'margin-left'
        - 'margin-collapse'
        - 'margin-top-collapse'
        - 'margin-right-collapse'
        - 'margin-bottom-collapse'
        - 'margin-left-collapse'
        - 'color'
        - 'font'
        - 'font-family'
        - 'font-size'
        - 'font-smoothing'
        - 'font-style'
        - 'font-weight'
        - 'text-align'
        - 'text-decoration'
        - 'text-indent'
        - 'text-overflow'
        - 'text-rendering'
        - 'text-size-adjust'
        - 'text-shadow'
        - 'text-transform'
        - 'line-height'
        - 'letter-spacing'
        - 'word-spacing'
        - 'word-break'
        - 'word-wrap'
        - 'white-space'
        - 'background'
        - 'background-attachment'
        - 'background-color'
        - 'background-image'
        - 'background-position'
        - 'background-repeat'
        - 'background-size'
        - 'border'
        - 'border-collapse'
        - 'border-top'
        - 'border-right'
        - 'border-bottom'
        - 'border-left'
        - 'border-color'
        - 'border-image'
        - 'border-top-color'
        - 'border-right-color'
        - 'border-bottom-color'
        - 'border-left-color'
        - 'border-spacing'
        - 'border-style'
        - 'border-top-style'
        - 'border-right-style'
        - 'border-bottom-style'
        - 'border-left-style'
        - 'border-width'
        - 'border-top-width'
        - 'border-right-width'
        - 'border-bottom-width'
        - 'border-left-width'
        - 'border-radius'
        - 'border-top-right-radius'
        - 'border-bottom-right-radius'
        - 'border-bottom-left-radius'
        - 'border-top-left-radius'
        - 'border-radius-topright'
        - 'border-radius-bottomright'
        - 'border-radius-bottomleft'
        - 'border-radius-topleft'
